import { TimelineEvent } from "../components/CanvasTimeline";

export const timelineStart = new Date("2024-12-01T08:00:00Z");

const TOTAL_DURATION_MS = 48 * 60 * 60 * 1000; // 48 hours
const TOTAL_EVENTS = 10_000;
const EVENT_INTERVAL_MS = TOTAL_DURATION_MS / TOTAL_EVENTS;
const COLOR_PALETTE = [
  "#7f5af0",
  "#ff6b6b",
  "#ffd166",
  "#06d6a0",
  "#118ab2",
  "#ef476f",
  "#ff9f1c",
  "#2ec4b6"
];

export const demoEvents: TimelineEvent[] = Array.from(
  { length: TOTAL_EVENTS },
  (_, index) => {
    const timestamp =
      timelineStart.getTime() + index * EVENT_INTERVAL_MS;
    const wave = Math.floor(index / 250) + 1; // 40 waves across dataset
    const color = COLOR_PALETTE[index % COLOR_PALETTE.length];
    const id = `evt-${String(index + 1).padStart(5, "0")}`;

    return {
      id,
      timestamp: new Date(timestamp).toISOString(),
      title: `Event #${index + 1}`,
      subtitle: `Wave segment ${wave}`,
      description: `Autogenerated telemetry marker ${index + 1}.`,
      wave,
      color
    };
  }
);

